서버에 Docker 컨테이너가 완전종료가 되지않아 생기는 오류 수정중
- 이전 컨테이너 삭제명령 추가
- 워크 플로우 실행 실패로 다시 푸시
- 주석 설정 이상으로 플로우 실행실패로 재수정
- stop -> kill  로 변경
- actions 버전 변경
- docker 컨테이너 버전관리를 위한 이전 컨테이너 삭제 명령 지움
- actions/setup-java@v3 에서는 distribution 옵션이 필수인가봄 check-latest 도 추가
- docker 를 이름/별명:태그 가 아니라 이름으로 관리하기로 하고 버전 관리를 위해서 이전 버전을 삭제하지 않기로함 또 버전 이름은 날짜를 넣기로 했음
- docker 실행이 안 되는데 workflow 가 정상이라고 떠서 || true 삭제
- || true 다시 추가 빌드와 푸쉬 할때에도 태그를 바꿔줘야 했었는데 손대지 않아 도커가 실행 안 된걸로 파악후 수정
- 푸시 와 빌드시 VERSION 값도 날짜로 밪춰서 수정
- 시간 기준으로 계속 VERSION 을 넣으면 차이나서 안 되기때문에 한 번 고정 시켜준다
- 시간이 맞나 확인하는 echo 설정

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -61,6 +61,7 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
             # EC2 내에서 동일한 버전 사용
+            echo "Using version: $VERSION"
             docker pull yawning5/ec2study:$VERSION
 
             # 'ec2study_$VERSION' 이름을 가진 컨테이너가 있으면 중지 및 삭제
@@ -71,7 +72,8 @@ jobs:
             fi
 
             # 새로운 버전의 컨테이너 실행
-            docker run --name ec2study_$VERSION -d -p 8080:8080 yawning5/ec2study:$VERSION
+            echo "Running new container with version: $VERSION"
+            docker run --name ec2study_$VERSION -d -p 8080:8080 yawning5/ec2study:$VERSION || echo "Error: Failed to run container"
 
             # 만약 이전 버전의 컨테이너가 존재한다면, 10개 이상 남기지 않도록 삭제
             OLD_CONTAINERS=$(docker ps -a -q --filter "name=ec2study_" | wc -l)
@@ -79,4 +81,3 @@ jobs:
               echo "Removing old containers..."
               docker ps -a -q --filter "name=ec2study_" | head -n -10 | xargs docker rm
             fi
-          debug: true
